# Generated by Django 4.2 on 2024-02-10 09:06

import Phonebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[Phonebook.models.validate_name])),
                ('last_name', models.CharField(max_length=50, validators=[Phonebook.models.validate_name])),
                ('phone_number', models.CharField(max_length=11, validators=[Phonebook.models.validate_phone_number])),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
